spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/challenge?useUnicode=true&charecterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.challengelog.pojo
  mapper-locations: classpath:challengelog/mapper/*.xml

